# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "marveldb2" ]
  pull_request:
    branches: [ "marveldb2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install all dependencies
      run:
        npm ci

    - name: npm deploy with gh-pages
      run: |
        git config user.name $user_name 
        git config user.email $user_email 
        git remote set-url origin https://x-access-token:${repo_token}@github.com/${repository}.git 
        npm run deploy
      env:
        user_name: "$GITHUB_ACTOR"
        user_email: "$GITHUB_ACTOR@bots.github.com"
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
